### PR TITLE
Make Python 3, Django 1.11 compatible, add tests

### PR DESCRIPTION
**Pull request by rhooper**
Merges in minor changes from other forks, and fixes the module to work with Django 1.11, Python 3.  Adds unit tests and tox suite including code linting and fixes.

### CODE REVIEW

**Comment by bufke** [comment]
Hello, this project is abandoned. Would you like to take it over?

**Comment by rhooper** [comment]
Sure, it seems to be the only one of it's kind out there.

**Comment by bufke** [comment]
Do you have a pypi username I can add?

**Comment by rhooper** [comment]
I was just about to ask.  `rhooper` there too, same at RTD.

**Comment by bufke** [comment]
Added

**Pull request merged**
